use_frameworks!

platform :ios, '14.0'

target 'FullScreenPopGesture_Example' do
  pod 'FullScreenPopGesture', :path => '../'

  target 'FullScreenPopGesture_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
